### ISSUE TITLE
unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by GadskyPapa** [bushvin/zabbix-kvm-res#10]
There isn't the encoding keyword in  json.dumps in python 3.x. I'm not a python hacker and don't know which python versions it works on. But it doesn't work on CentOS Linux release 8.3.2011 and the default python36. It works OK without encoding='utf-8'.

#./zabbix-libvirt-res.py --resource domain --action list
Traceback (most recent call last):
  File "./zabbix-libvirt-res.py", line 301, in <module>
    main()
  File "./zabbix-libvirt-res.py", line 81, in main
    r = json.dumps(list_to_zbx(dom.list(), '{#DOMAINNAME}'), sort_keys=True, encoding='utf-8', indent=2)
  File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by bushvin** [comment]
My original code was created for Python 2.7.5, so it was a bit old

encosind='UTF-8' appears to be the default after reading the doc.

Can you please test?
